# Generated by Django 2.2.6 on 2020-04-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0003_enrollment_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='event_id',
            new_name='enroll_id',
        ),
    ]
