# Generated by Django 2.2.6 on 2020-04-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_auto_20200430_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enroll_id',
        ),
    ]
