# Generated by Django 2.2.6 on 2020-05-01 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0008_enrollment_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seats',
        ),
    ]
