# Generated by Django 3.0.4 on 2020-03-29 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=200)),
                ('form_1', models.ImageField(upload_to='files/%Y/%m/%d/')),
                ('form_2', models.ImageField(upload_to='files/%Y/%m/%d/')),
                ('form_3', models.ImageField(upload_to='files/%Y/%m/%d/')),
                ('form_4', models.ImageField(upload_to='files/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
