# Generated by Django 3.0.4 on 2020-03-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_1',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_2',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_3',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_4',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
