# Generated by Django 3.0.4 on 2020-03-30 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200329_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('form_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('upload_form', models.ImageField(blank=True, upload_to='uploadedfiles/%Y/%m/%d/')),
                ('comments', models.TextField()),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
