# Generated by Django 2.2.6 on 2020-04-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200330_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='form_1',
            new_name='form',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='form_2',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='form_3',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='form_4',
        ),
    ]
