# Generated by Django 2.2.6 on 2020-04-13 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200412_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('upload_form', models.FileField(blank=True, upload_to='uploadedfiles/%Y/%m/%d/')),
                ('comments', models.TextField()),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
